name: Go
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  deploying-lambda:
    - uses: hnucamendi/shared-gha-workflows/.github/workflows/deploy-lambda.yml@master
      with:
        runtime: 'Go'
        runtime-version: '1.22'
        function-name: 'ws-colly'
        function-directory: './functions/scraper'
