name: Deploy Given Version
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  deploy-lambda:
    uses: hnucamendi/shared-gha-workflows/.github/workflows/deploy-given-version.yml
    with:
      version_tag: "todo"
      environment: "development"
      lambda_name: "ws-colly"
      runtime-version: "1.22"
      gha_oidc_iam_role_name: "todo"
      subdirectory: "."
