name: Deploy Given Version
on:
  release:
    types: [published, prereleased]
jobs:
  deploy-lambda:
    uses: hnucamendi/shared-gha-workflows/.github/workflows/deploy-given-version.yml@master
    with:
      version_tag: "todo"
      environment: "development"
      lambda_name: "ws-colly"
      runtime-version: "1.22"
      subdirectory: "."
